---
- name: Deploy Laravel application to Yandex Cloud
  hosts: 51.250.111.163
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - docker.io
        - docker-compose

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing Docker container
      docker_container:
        name: user-crud-app
        state: stopped
        force_kill: yes

    - name: Remove existing Docker container
      docker_container:
        name: user-crud-app
        state: absent

    - name: Pull the latest Docker image
      docker_image:
        name: kash1ma/user-crud-app
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: user-crud-app
        image: kash1ma/user-crud-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Restart Docker
      service:
        name: docker
        state: restarted
