name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, sqlite3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install npm and composer dependencies
        run: make install

      - name: Run Duster
        run: vendor/bin/duster lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, sqlite3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install npm and composer dependencies
        run: make install

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run pwd
        run: pwd

      - name: Add database path to .env
        run: echo 'DB_DATABASE=/home/runner/work/hexletProject/hexletProject/database/database.sqlite' >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate

      - name: Run build
        run: make build

      - name: Run tests
        run: make test
